all:
	g++ -o run run.cpp tools/tools.cpp tools/process.cpp FCFS/FCFSQueue.cpp FCFS/fcfsDriver.cpp SJF/SJF.cpp SJF/sjfDriver.cpp STR/STR.cpp STR/strDriver.cpp RR/RR.cpp RR/rrDriver.cpp HPFS/HPFS_NP_driver.cpp HPFS/HPFS_Non_Preemptive.cpp HPFS/HPFS_P_driver.cpp HPFS/HPFS_Preemptive.cpp HPFS/HPFS.cpp
